set_property SRC_FILE_INFO {cfile:D:/Users/178633/Desktop/pulsadorAntirrebote/pulsadorAntirrebote.srcs/constrs_1/imports/Downloads/Basys-3-Master.xdc rfile:../../../pulsadorAntirrebote.srcs/constrs_1/imports/Downloads/Basys-3-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {btn_out}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports btn_in]
